language: rust
rust: stable
cache: cargo

os: osx
env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
script:
  - cargo build --release --target $TARGET --locked
  - cargo test --verbose

# before_deploy:
# ${TRAVIS_BUILD_DIR}/target/${TARGET}/release/noteexplorer
# noteexplorer-${TRAVIS_TAG}
